package loader

import (
	"fmt"
	"log"
	"os"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/perf"
	"github.com/cilium/ebpf/rlimit"
)

// Loader manages loading and attaching BPF programs.
type Loader struct {
	collection *ebpf.Collection
	links      []link.Link
	perfReader *perf.Reader
	closed     bool
}

// BPF program and map names (must match elkeid.bpf.c)
const (
	// Maps
	mapEvents     = "events"
	mapConfigMap  = "config_map"
	mapProcInfo   = "proc_info_map"
	mapTaskInfo   = "task_info_map"
	mapBufs       = "bufs"
	mapArgsMap    = "args_map"
	mapPidFilter  = "pid_filter"
	mapCommFilter = "comm_filter"
	mapProgArray  = "prog_array"

	// Programs - raw tracepoints
	progSchedProcessExec = "elkeid_sched_process_exec"
	progSchedProcessExit = "elkeid_sched_process_exit"

	// Programs - kprobes
	progSecuritySocketConnect    = "elkeid_security_socket_connect"
	progSecuritySocketConnectRet = "elkeid_security_socket_connect_ret"
	progInetCskAcceptRet         = "elkeid_inet_csk_accept_ret"
	progSecuritySocketBind       = "elkeid_security_socket_bind"
	progSecurityFileOpen        = "elkeid_security_file_open"
	progSecurityInodeUnlink     = "elkeid_security_inode_unlink"
	progSecurityInodeRename     = "elkeid_security_inode_rename"
	progSecurityInodeSymlink    = "elkeid_security_inode_symlink"
	progSecuritySbMount         = "elkeid_security_sb_mount"
	progSecurityFileMprotect    = "elkeid_security_file_mprotect"
	progDoInitModule            = "elkeid_do_init_module"
	progCommitCreds             = "elkeid_commit_creds"
	progCallUsermodehelper      = "elkeid_call_usermodehelper"

	// Programs - tracepoints
	progSysEnterKill        = "tracepoint_sys_enter_kill"
	progSysEnterTkill       = "tracepoint_sys_enter_tkill"
	progSysEnterPtrace      = "tracepoint_sys_enter_ptrace"
	progSysEnterPrctl       = "tracepoint_sys_enter_prctl"
	progSysEnterMemfdCreate = "tracepoint_sys_enter_memfd_create"
	progSysEnterSetsid      = "tracepoint_sys_enter_setsid"

	// Programs - additional kprobes
	progSecurityInodeCreate  = "elkeid_security_inode_create"
	progSecurityPathRmdir    = "elkeid_security_path_rmdir"
	progVfsWrite             = "elkeid_vfs_write"
	progUdpSendmsg           = "elkeid_udp_sendmsg"
	progSecurityInodeSetattr = "elkeid_security_inode_setattr"
	progSecurityInodeLink    = "elkeid_security_inode_link"
)

// LoaderConfig contains configuration options for the loader.
type LoaderConfig struct {
	BPFObjectPath  string // Path to compiled BPF object file (empty = use embedded)
	PerfBufferSize int    // Size of perf buffer in pages (default: 128)
	UseEmbedded    bool   // Use embedded BPF bytecode (default: true if available)
}

// DefaultConfig returns a default loader configuration.
func DefaultConfig() *LoaderConfig {
	return &LoaderConfig{
		BPFObjectPath:  "",
		PerfBufferSize: 128,
		UseEmbedded:    true,
	}
}

// NewLoader creates a new BPF loader with the given configuration.
func NewLoader(cfg *LoaderConfig) (*Loader, error) {
	if cfg == nil {
		cfg = DefaultConfig()
	}

	// Remove memlock limit for BPF
	if err := rlimit.RemoveMemlock(); err != nil {
		return nil, fmt.Errorf("failed to remove memlock: %w", err)
	}

	var spec *ebpf.CollectionSpec
	var err error

	// Try to load BPF program
	if cfg.UseEmbedded {
		// Try embedded bytecode first (generated by bpf2go)
		spec, err = loadEmbeddedSpec()
		if err != nil {
			// Fallback to file if embedded not available
			if cfg.BPFObjectPath != "" {
				spec, err = loadFromFile(cfg.BPFObjectPath)
			} else {
				// Try default paths
				for _, path := range []string{
					"/usr/local/share/elkeid/bpf/elkeid.bpf.o",
					"./bpf/elkeid.bpf.o",
					"./elkeid.bpf.o",
				} {
					spec, err = loadFromFile(path)
					if err == nil {
						break
					}
				}
			}
		}
	} else if cfg.BPFObjectPath != "" {
		spec, err = loadFromFile(cfg.BPFObjectPath)
	}

	if err != nil {
		return nil, fmt.Errorf("failed to load BPF spec: %w", err)
	}
	if spec == nil {
		return nil, fmt.Errorf("no BPF program available")
	}

	log.Println("[loader] Creating BPF collection (tolerant mode)...")

	// First try full collection load
	coll, err := ebpf.NewCollection(spec)
	if err != nil {
		log.Printf("[loader] Full collection load failed: %v", err)
		log.Println("[loader] Falling back to tolerant per-program loading...")

		// Reload spec fresh
		spec, err = loadEmbeddedSpec()
		if err != nil {
			return nil, fmt.Errorf("failed to reload spec: %w", err)
		}

		// Create maps first, then load programs individually
		opts := ebpf.CollectionOptions{}
		coll, err = loadTolerant(spec, opts)
		if err != nil {
			return nil, fmt.Errorf("failed to create BPF collection (tolerant): %w", err)
		}
	} else {
		log.Println("[loader] BPF collection created successfully")
	}

	// Create perf reader for events map
	eventsMap := coll.Maps[mapEvents]
	if eventsMap == nil {
		coll.Close()
		return nil, fmt.Errorf("events map not found")
	}

	perfReader, err := perf.NewReader(eventsMap, cfg.PerfBufferSize*os.Getpagesize())
	if err != nil {
		coll.Close()
		return nil, fmt.Errorf("failed to create perf reader: %w", err)
	}

	return &Loader{
		collection: coll,
		links:      make([]link.Link, 0),
		perfReader: perfReader,
	}, nil
}

// loadTolerant creates a Collection, skipping programs that fail verifier checks.
func loadTolerant(spec *ebpf.CollectionSpec, opts ebpf.CollectionOptions) (*ebpf.Collection, error) {
	// Keep trying: remove the failing program from the spec and retry.
	// This lets all maps and non-failing programs load successfully.
	for attempts := 0; attempts < 30; attempts++ {
		coll, err := ebpf.NewCollectionWithOptions(spec, opts)
		if err == nil {
			return coll, nil
		}

		// Extract failing program name from error message
		errMsg := err.Error()
		removed := false
		for name := range spec.Programs {
			if len(name) > 0 && contains(errMsg, "program "+name+":") {
				log.Printf("[loader] Skipping program %s (verifier rejected)", name)
				delete(spec.Programs, name)
				removed = true
				break
			}
		}
		if !removed {
			return nil, err
		}
	}
	return nil, fmt.Errorf("too many program failures")
}

func contains(s, substr string) bool {
	return len(s) >= len(substr) && (s == substr || len(substr) == 0 ||
		(len(s) > 0 && stringContains(s, substr)))
}

func stringContains(s, substr string) bool {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return true
		}
	}
	return false
}

// loadFromFile loads BPF spec from a file.
func loadFromFile(path string) (*ebpf.CollectionSpec, error) {
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return nil, fmt.Errorf("BPF object file not found: %s", path)
	}
	return ebpf.LoadCollectionSpec(path)
}

// loadEmbeddedSpec is defined in platform-specific files:
// - loader_linux.go: Uses bpf2go generated code
// - loader_other.go: Returns nil (fallback to file loading)

// Attach attaches all BPF programs to their hooks.
func (l *Loader) Attach() error {
	if l.closed {
		return fmt.Errorf("loader is closed")
	}

	var err error

	// Attach raw tracepoints
	if err = l.attachRawTracepoint("sched_process_exec", progSchedProcessExec); err != nil {
		return err
	}
	if err = l.attachRawTracepoint("sched_process_exit", progSchedProcessExit); err != nil {
		return err
	}

	// Attach kprobes
	kprobes := map[string]string{
		"security_socket_connect": progSecuritySocketConnect,
		"security_socket_bind":    progSecuritySocketBind,
		"security_file_open":      progSecurityFileOpen,
		"security_inode_unlink":   progSecurityInodeUnlink,
		"security_inode_rename":   progSecurityInodeRename,
		"security_inode_symlink":  progSecurityInodeSymlink,
		"security_sb_mount":       progSecuritySbMount,
		"security_file_mprotect":  progSecurityFileMprotect,
		"do_init_module":          progDoInitModule,
		"commit_creds":            progCommitCreds,
		"call_usermodehelper":     progCallUsermodehelper,
		"security_inode_create":   progSecurityInodeCreate,
		"security_path_rmdir":     progSecurityPathRmdir,
		"vfs_write":               progVfsWrite,
		"udp_sendmsg":             progUdpSendmsg,
		"security_inode_setattr":  progSecurityInodeSetattr,
		"security_inode_link":     progSecurityInodeLink,
	}

	for symbol, progName := range kprobes {
		if err = l.attachKprobe(symbol, progName); err != nil {
			log.Printf("[loader] Warning: failed to attach kprobe %s: %v", symbol, err)
		}
	}

	// Attach kretprobes
	kretprobes := map[string]string{
		"security_socket_connect": progSecuritySocketConnectRet,
		"inet_csk_accept":         progInetCskAcceptRet,
	}
	for symbol, progName := range kretprobes {
		if err = l.attachKretprobe(symbol, progName); err != nil {
			log.Printf("[loader] Warning: failed to attach kretprobe %s: %v", symbol, err)
		}
	}

	// Attach tracepoints
	tracepoints := map[string]struct {
		category string
		name     string
		prog     string
	}{
		"kill":         {"syscalls", "sys_enter_kill", progSysEnterKill},
		"tkill":        {"syscalls", "sys_enter_tkill", progSysEnterTkill},
		"ptrace":       {"syscalls", "sys_enter_ptrace", progSysEnterPtrace},
		"prctl":        {"syscalls", "sys_enter_prctl", progSysEnterPrctl},
		"memfd_create": {"syscalls", "sys_enter_memfd_create", progSysEnterMemfdCreate},
		"setsid":       {"syscalls", "sys_enter_setsid", progSysEnterSetsid},
	}

	for name, tp := range tracepoints {
		if err = l.attachTracepoint(tp.category, tp.name, tp.prog); err != nil {
			log.Printf("[loader] Warning: failed to attach tracepoint %s: %v", name, err)
		}
	}

	return nil
}

// attachRawTracepoint attaches a raw tracepoint program.
func (l *Loader) attachRawTracepoint(tpName, progName string) error {
	prog := l.collection.Programs[progName]
	if prog == nil {
		return fmt.Errorf("program %s not found", progName)
	}

	lnk, err := link.AttachRawTracepoint(link.RawTracepointOptions{
		Name:    tpName,
		Program: prog,
	})
	if err != nil {
		return fmt.Errorf("failed to attach raw tracepoint %s: %w", tpName, err)
	}

	l.links = append(l.links, lnk)
	return nil
}

// attachKprobe attaches a kprobe program.
func (l *Loader) attachKprobe(symbol, progName string) error {
	prog := l.collection.Programs[progName]
	if prog == nil {
		return fmt.Errorf("program %s not found", progName)
	}

	lnk, err := link.Kprobe(symbol, prog, nil)
	if err != nil {
		return fmt.Errorf("failed to attach kprobe %s: %w", symbol, err)
	}

	l.links = append(l.links, lnk)
	return nil
}

// attachKretprobe attaches a kretprobe program.
func (l *Loader) attachKretprobe(symbol, progName string) error {
	prog := l.collection.Programs[progName]
	if prog == nil {
		return fmt.Errorf("program %s not found", progName)
	}

	lnk, err := link.Kretprobe(symbol, prog, nil)
	if err != nil {
		return fmt.Errorf("failed to attach kretprobe %s: %w", symbol, err)
	}

	l.links = append(l.links, lnk)
	return nil
}

// attachTracepoint attaches a tracepoint program.
func (l *Loader) attachTracepoint(category, name, progName string) error {
	prog := l.collection.Programs[progName]
	if prog == nil {
		return fmt.Errorf("program %s not found", progName)
	}

	lnk, err := link.Tracepoint(category, name, prog, nil)
	if err != nil {
		return fmt.Errorf("failed to attach tracepoint %s/%s: %w", category, name, err)
	}

	l.links = append(l.links, lnk)
	return nil
}

// PerfReader returns the perf buffer reader.
func (l *Loader) PerfReader() *perf.Reader {
	return l.perfReader
}

// Collection returns the BPF collection for direct map access.
func (l *Loader) Collection() *ebpf.Collection {
	return l.collection
}

// SetConfig updates the BPF configuration map.
func (l *Loader) SetConfig(rootPidNS uint32, options uint32) error {
	configMap := l.collection.Maps[mapConfigMap]
	if configMap == nil {
		return fmt.Errorf("config map not found")
	}

	type elkeidConfig struct {
		RootPidNS uint32
		Options   uint32
	}

	key := uint32(0)
	value := elkeidConfig{
		RootPidNS: rootPidNS,
		Options:   options,
	}

	return configMap.Update(key, value, ebpf.UpdateAny)
}

// SetEventEnabled enables or disables a specific event by ID.
// When enabled=false, the BPF hook will skip this event type entirely.
func (l *Loader) SetEventEnabled(eventID uint32, enabled bool) error {
	filterMap := l.collection.Maps["event_filter"]
	if filterMap == nil {
		return fmt.Errorf("event_filter map not found")
	}
	val := uint8(1)
	if !enabled {
		val = 0
	}
	return filterMap.Update(eventID, val, ebpf.UpdateAny)
}

// AddPIDWhitelist adds a PID to the whitelist (events from this PID will be skipped).
func (l *Loader) AddPIDWhitelist(pid uint32) error {
	filterMap := l.collection.Maps["pid_filter"]
	if filterMap == nil {
		return fmt.Errorf("pid_filter map not found")
	}
	val := uint8(1)
	return filterMap.Update(pid, val, ebpf.UpdateAny)
}

// RemovePIDWhitelist removes a PID from the whitelist.
func (l *Loader) RemovePIDWhitelist(pid uint32) error {
	filterMap := l.collection.Maps["pid_filter"]
	if filterMap == nil {
		return fmt.Errorf("pid_filter map not found")
	}
	return filterMap.Delete(pid)
}

// Close releases all resources.
func (l *Loader) Close() error {
	if l.closed {
		return nil
	}
	l.closed = true

	var errs []error

	// Close perf reader
	if l.perfReader != nil {
		if err := l.perfReader.Close(); err != nil {
			errs = append(errs, fmt.Errorf("failed to close perf reader: %w", err))
		}
	}

	// Detach all links
	for _, lnk := range l.links {
		if err := lnk.Close(); err != nil {
			errs = append(errs, fmt.Errorf("failed to close link: %w", err))
		}
	}

	// Close collection
	if l.collection != nil {
		l.collection.Close()
	}

	if len(errs) > 0 {
		return fmt.Errorf("errors during close: %v", errs)
	}

	return nil
}
